### ISSUE TITLE
Checkout block support?

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-gateway-dummy#11]
When the gateway is enabled I see it as an option in the checkout shortcode, but not in the checkout block.

**Comment by jimjasson** [comment]
Hey @helgatheviking 👋

Tried this in a clean WP install and the Dummy Payments gateway showed up as expected in the checkout block. 

Can you please make sure that you are using the latest Dummy Payments [release](https://github.com/woocommerce/woocommerce-gateway-dummy/releases/tag/1.0.3)? 

If you have cloned the repository and you are in the latest `master`, then please make sure that you have built the project by running `npm install` and `npm run build`. 

If you have done all that and you still see this issue, then could you please let me know if you see any JS errors in the console while you are in the checkout block?

**Comment by helgatheviking** [comment]
Thanks Jason! I needed to update to 1.0.3.
