### ISSUE TITLE
Blocks Support not working

### ISSUE THREAD

**Issue by zakitekhqs** [woocommerce/woocommerce-gateway-dummy#19]
I have tried the plugin but it seems block support is not working.

Steps:
-I installed the plugin
-I installed woo blocks plugin.

then I add checkout block with Gutenberg but  it says extension is not compatible with woo checkout based block.

**Comment by jimjasson** [comment]
Hey @zakitekhqs, 

Thank you for getting in touch! 

I created a fresh site and I installed Dummy Payments. Then, I added the checkout block in the checkout page. 

As you can see in this screenshot:

 ![RSqAr5.png](https://github.com/woocommerce/woocommerce-gateway-dummy/assets/25955483/00d78b93-aac1-4662-b25c-4e91483360cf)

Dummy Payments showed up without issues in the checkout page. 

> but it says extension is not compatible with woo checkout based block.

Could you please share a screenshot of the error you see? Do you continue to see this issue when only WooCommerce + Dummy Payments are active and a default WordPress theme, like Twenty Twenty Three, is used?

**Comment by zakitekhqs** [comment]
Please check screenshot
![Screenshot from 2023-09-12 20-05-34](https://github.com/woocommerce/woocommerce-gateway-dummy/assets/144108507/2f552e76-6410-46fa-b510-fea4f2f4cac4)

Do I need to do something specifically after installingplugin?

**Comment by zakitekhqs** [comment]
I wanted to add more details.

-I did not run npm.

And If I have custom plugin(payment method) and if npm is required do we need to run it?

**Comment by jimjasson** [comment]
Hey @zakitekhqs, 

Thanks for the update! 

You may download pre-built, plug and play versions of the plugin from: https://github.com/woocommerce/woocommerce-gateway-dummy/releases/tag/1.0.5

See: ![RKHjq9.png](https://github.com/woocommerce/woocommerce-gateway-dummy/assets/25955483/990bac56-4be0-4a7d-9b9c-3a952e6f085c)

If you decide to create your own custom plugin in the future, then you need to release a zip version that contains all the built files. Therefore, run the build commands on your project and then create a zip that includes all built files.
