### ISSUE TITLE
Third Party Payment Gateway

### ISSUE THREAD

**Issue by zakitekhqs** [woocommerce/woocommerce-gateway-dummy#20]
Hi, I am sorry for bothering again.

I have third party plugin ( a payment gateway).

Well I added the Block support for checkout, it is compatible but I have a payment form which being generated fine with short code based checkout but in checkout block it just takes the plugin title and checkbox for future save but not showing my form

I am going to attach JS, Can you please have a look into it, that would be great as it is very important and urgent for me.

Thanks

![Screenshot from 2023-09-15 11-39-14](https://github.com/woocommerce/woocommerce-gateway-dummy/assets/144108507/b2b6ab60-6181-466a-baa7-baaa65f2da88)

[blocks-js.txt](https://github.com/woocommerce/woocommerce-gateway-dummy/files/12616373/blocks-js.txt)
[php.txt](https://github.com/woocommerce/woocommerce-gateway-dummy/files/12616374/php.txt)

**Comment by jimjasson** [comment]
Hey @zakitekhqs, 

Thank you for the question! 

As far as I understand, you are developing your own Payment Gateway and are looking to make it work with the block-based checkout, but you are running into some issues. Is that right?

If so, then I recommend posting your question to the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) -- that's the best place to ask technical questions about WooCommerce! Also, there are many experienced developers who can help you resolve compatibility issues with Blocks.
