### ISSUE TITLE
Feature request: Only show if admin option

### ISSUE THREAD

**Issue by NickGreen** [woocommerce/woocommerce-gateway-dummy#21]
It would be really nice to be able to test the dummy gateway on a production site without it affecting normal customers. One way to do that would be to add an option to "only show gateway at checkout if logged in and an admin."

**Comment by NickGreen** [comment]
We could add a checkbox in the settings screen like this:
```php
'hide_for_non_admin_users' => array(
    'type'    => 'checkbox',
    'label'   => __( 'Hide at checkout for non-admin users', 'woocommerce-gateway-dummy' ),
    'default' => 'no'
),
```

Then change the add_gateways function to:
```php
public static function add_gateway( $gateways ) {
   $hide_for_non_admin_users = get_option( 'hide_for_non_admin_users', 'no' );
   if ( ( 'yes' === $hide_for_non_admin_users && current_user_can( 'manage_options' ) ) || 'no' === $hide_for_non_admin_users ) {
        $gateways[] = 'WC_Gateway_Dummy';
    }
    return $gateways;
}
```

What do you think, @jimjasson ?

**Comment by jimjasson** [comment]
That's such a clever idea @NickGreen! Thanks for sharing and for including some code as well! 

I am adding this to our team's backlog so we can have a look in one of the upcoming cooldowns!

**Comment by NickGreen** [comment]
If you guys get too backed up, feel free to give me repo access, and I could work out a PR for you.

**Comment by jimjasson** [comment]
Hey @NickGreen -- that would be awesome! Thanks! 

You should have write access to this repository, as it is public. Let me know if you run into any issues pushing code in this repo.

**Comment by NickGreen** [comment]
@jimjasson When I try to create a new feature branch, I get this warning:

> It looks like you don't have write access ...

<img width="292" alt="SCR-20230927-kzaj" src="https://github.com/woocommerce/woocommerce-gateway-dummy/assets/2067992/0c407aff-382b-4568-b76d-f70114cf44e3">

**Comment by jimjasson** [comment]
@NickGreen Hmm, that's odd! I went ahead and specifically gave write access to your user -- mind trying again?

**Comment by NickGreen** [comment]
Thanks, that worked! Pull request up here, I'll request your review :) : https://github.com/woocommerce/woocommerce-gateway-dummy/pull/22

**Comment by jimjasson** [comment]
Closed via: https://github.com/woocommerce/woocommerce-gateway-dummy/pull/22
