### ISSUE TITLE
Get cart totals on JS

### ISSUE THREAD

**Issue by seldimi** [woocommerce/woocommerce-gateway-dummy#28]
Hello
import { useCart } from '@woocommerce/blocks-checkout';
Can you give an example or least document how to get the cart (eg cart totals, as the above one fails

**Comment by PanosSynetos** [comment]
@senadir could you maybe help here? Thanks!

**Comment by mikejolley** [comment]
Hi,

The `@woocommerce/blocks-checkout` package exports only some components that payment methods can use. `useCart` does not exist—I'm not sure where you saw that example.

How you access cart totals depends on your use case. They are available from the REST API, or some components are passed these values for context. For example, payment methods will be given the cart totals and customer address information.

I'd suggest starting here:

https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility

And for payment method specifically look here:

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md

An example of cart data, if you look at the `canMakePayment` method, its passed a cart object which holds everything you need:

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#canmakepayment-required

I will mark this closed as this is unrelated to this repository. You can ask questions on WooCommerce Community Slack if you need further assistance. Thanks

**Comment by seldimi** [comment]
Hello.
Yes I understood this is not a support channel, but that would be handy for those who are not familiar with NodeJS but expertise on the PHP part of the gateway. We built over 15 gateways with the classic way, and now we're forced to do the same interface on NodeJS as well, so if you could provide an example, that would be really appreciated.

I've understood that canMakePayment function can hold CartTotals variable, but what if i want to design an selectbox depending on the cart total on Content of the const Dummy, before sending it to registerPaymentMethod

**Comment by mikejolley** [comment]
@seldimi there are examples in the resources I listed and in this repository https://github.com/woocommerce/woocommerce-gateway-dummy/blob/751ae04e3b5cbeba8e639e4a72b8a600f2936d63/resources/js/frontend/index.js#L46

`content` is also provided with the [context you require.](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#props-fed-to-payment-method-nodes)
