### ISSUE TITLE
Incompatible archive

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-gateway-dummy#33]
Just tried to upload 1.0.8 to a live test site and got the incompatible archive error.

**Comment by PanosSynetos** [comment]
Please send a screenshot too and any console errors, thanks Kathy!

**Comment by helgatheviking** [comment]
Redownloaded and it's working fine today. Have you tried turning yourself off and back on again? :woman_facepalming:

**Comment by PanosSynetos** [comment]
Hahahah!!! Happens to the best of us :)
