### ISSUE TITLE
Unable to build Wordpress 6.5.2 and Woocommerce 8.8.2

### ISSUE THREAD

**Issue by arijit-sezzle** [woocommerce/woocommerce-gateway-dummy#35]
I get this error when I do `wp-scripts build`

[webpack-cli] Failed to load '/Applications/MAMP/htdocs/wordpress/wp-content/plugins/woocommerce-gateway-dummy/webpack.config.js' config
[webpack-cli] Error: Cannot find module '../assets/packages'

Any idea how to fix this?

**Comment by chang-ryan** [comment]
seeing this too

**Comment by arijit-sezzle** [comment]
It's actually coming from the `@woocommerce/dependency-extraction-webpack-plugin`. And the reason is that 2.4.0(^2.2.0 goes to 2.4.0)  of `@woocommerce/dependency-extraction-webpack-plugin` does not contain `assets/packages` folder and it is required inside the `src/index.js` of `@woocommerce/dependency-extraction-webpack-plugin`. Just using `2.2.0` works.

**Comment by chang-ryan** [comment]
ah yes, updating to `3.0.0` also works

**Comment by jimjasson** [comment]
Thank you all for reporting this! 

We have opened a PR with a fix.
