### ISSUE TITLE
getSettings doesn't work

### ISSUE THREAD

**Issue by henriqueccruz** [woocommerce/woocommerce-gateway-dummy#42]
I've been trying to implement block-based checkout on a payment gateway which I mantain and I couldn't help noticing that even on this gateway, the getSetting function always returns false and the Payment Gateway ends up showing only because it has a fallback label defined.

As shown on #34 , the user defines the gateway name but the default keeps being used.
Also, window.wc.wcSettings.getSetting('dummy_data') always returns false on the frontend.

Is this an expected behaviour? Or am I missing something?

**Comment by henriqueccruz** [comment]
For some unkown reason, /src/Blocks/BlockTypes/Checkout.php:456 was commented out on my download of Woocommerce v8.9.1
Uncommented it and all seemed to work fine.

**Comment by xristos3490** [comment]
Hey @henriqueccruz! 

> For some unkown reason, /src/Blocks/BlockTypes/Checkout.php:456 was commented out on my download of Woocommerce v8.9.1

I double-checked whether there is an issue with the latest WooCommerce package, but these lines look as expected, so perhaps something on your end caused this. I'm glad you figured it out!  :) 

Nevertheless, a few details about this package:
- Only works on frontend; other requests should always end up as `false` 
- It specifically uses the data provided in the [get_payment_method_data](https://github.com/woocommerce/woocommerce-gateway-dummy/blob/54ea9bd2eee55bebdb38bcf9cb34f9ab1d764a21/includes/blocks/class-wc-dummy-payments-blocks.php#L79-L85) under the `AbstractPaymentMethodType` interface.

Hope this helps!

**Comment by henriqueccruz** [comment]
Besides this problem with getSettings, I had a few more issues with my gateway not showing up on the checkout.
It was related with the is_available function on the main gateway class.
These functions were proven useful for debugging:
`wp.data.select('wc/store/payment').getAvailablePaymentMethods()`
`wp.data.select('wc/store/payment').getAvailableExpressPaymentMethods()`
`window.wcSettings.allSettings`

Thanks for the reply nonetheless.
